'use strict';

export const RECEIVE_ALBUMS_FROM_SERVER = 'RECEIVE_ALBUMS_FROM_SERVER';
export const RECEIVE_ARTISTS_FROM_SERVER = 'RECEIVE_ARTISTS_FROM_SERVER';
export const RECEIVE_SINGLE_ARTIST_FROM_SERVER = 'RECEIVE_SINGLE_ARTIST_FROM_SERVER';

export const START_PLAYING = 'START_PLAYING';
export const STOP_PLAYING = 'STOP_PLAYING';
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const SET_CURRENT_ALBUM = 'SET_CURRENT_ALBUM';

export const RECEIVE_NEW_PLAYLIST = 'RECEIVE_NEW_PLAYLIST';
export const RECEIVE_ALL_PLAYLIST = 'RECEIVE_ALL_PLAYLIST';
export const RECEIVE_SINGLE_PLAYLIST = 'RECEIVE_SINGLE_PLAYLIST';
export const UPDATE_SINGLE_PLAYLIST = 'UPDATE_SINGLE_PLAYLIST';
export const DELETE_SONG_PLAYLIST = 'DELETE_SONG_PLAYLIST';


export const RECEIVE_ALL_SONGS = 'RECEIVE_ALL_SONGS';

export const SERVER_ERROR = 'SERVER_ERROR';
export const RESET_ERROR = 'RESET_ERROR';